### ISSUE TITLE
Оптимістичні статті

### ISSUE THREAD

**Issue by volodymyr-kushnir** [kate-veryha/bsa-lecture-1#2]
@kate-veryha, серед ночі, так?
Ну гаразд, закоммітиш оптимістичні статті (пошвидше би), то познач цю проблему як вирішену, будь ласка. Також ось тобі [**кілька лайфхаків**](https://github.com/volodymyr-kushnir/agenda) в поміч.

P. S. Оу, вони вже є іншою гілкою. Окєй, то вже в кінці закриєш цю проблему тоді, коли замерджиш до `master`.

**Comment by kate-veryha** [comment]
@volodymyr-kushnir, дякую за лайфхаки. 
Вмерджила

**Comment by volodymyr-kushnir** [comment]
Fixed with c33b8ba4515dffb2fe42f31a0fb7a1265a3d154e, issue resolved 🎉
